# image: ruby2.3.1
# script:
#   - cp config/database.drone.yml config/database.yml
#   - mkdir -p /tmp/bundler
#   - sudo chown ubuntu:ubuntu /tmp/bundler
#   - bundle install --path=/tmp/bundler --deployment --quiet
#   - psql -c 'create database test;' -U postgres -h 127.0.0.1
#   # - mysql -u root -h127.0.0.1 -P 3306 -e 'create database rails_app_test;'
#   # - mysql -u root -h127.0.0.1 -P 3306 -D rails_app_test < ./db/structure.sql
#   - bundle exec rspec spec
#   #
#   # - bundle install
#   # - bundle exec rake parallel:create
#   # - bundle exec rake parallel:prepare
#   # - bundle exec rake parallel:spec
# notify:
#   email:
#     recipients:1
#       - corey@jtrpfurniture.com


pipeline:
  build:
    image: ruby:2.3.1
    commands:
      - curl --output /usr/local/bin/phantomjs https://s3.amazonaws.com/circle-downloads/phantomjs-2.1.1
      - mkdir -p /tmp/bundler
      - gem install bundler
      - bundle install --path=/tmp/bundler --jobs 8
      - bundle exec rake db:create
      - bundle exec rake db:schema:load
      - bundle exec rake parallel:create
      - bundle exec rake parallel:prepare
      - bundle exec rake parallel:spec
    environment:
      - COVERALLS_REPO_TOKEN=STrTk0bX8zdok8Vkv21eHRqqUUchSmsi7
      - AWS_ACCESS_KEY_ID=AKIAJKGFDP4MI3SJBKOA
      - AWS_SECRET_ACCESS_KEY=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
      - CLOVER_URL=https://api.clover.com
      - CLOVER_API_URL=https://apisandbox.dev.clover.com
      - CLOVER_APP_ID=6MSHVYBH9MSJC
      - CLOVER_APP_SECRET=76f10de7-6cc3-6e66-7172-c2c248ad9bb2
      - CLOVER_MERCHANT_ID=HFBW9FH45ZBH2
      - CLOVER_API_TOKEN=285036e1-d1a8-dfc6-fe5c-51babdd7d241
      - CLOVER_WEBHOOK_AUTH_CODE=5388b971-527e-49d5-aec7-9e9dcd17652a
      - CLOUDINARY_CLOUD_NAME=some_id
      - CLOUDINARY_API_KEY=some_key
      - CLOUDINARY_API_SECRET=some_secret
      - CLOUDINARY_DEFAULT_IMAGE_ID=ryiswhs6a6gb08zxmk0w
      - GEMNASIUM_TESTSUITE=rspec spec
      - GEMNASIUM_PROJECT_SLUG=github.com/cpsoinos/jtrp
      - GEMNASIUM_TOKEN=b38fa1f918ac0bc093e48975e57e88c0
      - HOST=https://somehost.com
      - LOB_API_KEY=test_f0d71df35dd567eccdb31ced4cdaf1fb046
      - LOB_BANK_KEY=bank_a33a6d2dacae8cf
      - LOB_COMPANY_ADDRESS_KEY=adr_cda4a50721394d23

services:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

cache:
  mount:
    - /tmp/bundler
    - .git
