image: ruby2.3.1
script:
  - cp config/database.drone.yml config/database.yml
  - mkdir -p /tmp/bundler
  - sudo chown ubuntu:ubuntu /tmp/bundler
  - bundle install --path=/tmp/bundler --deployment --quiet
  - psql -c 'create database test;' -U postgres -h 127.0.0.1
  # - mysql -u root -h127.0.0.1 -P 3306 -e 'create database rails_app_test;'
  # - mysql -u root -h127.0.0.1 -P 3306 -D rails_app_test < ./db/structure.sql
  - bundle exec rspec spec
  #
  #
  # - bundle install
  # - bundle exec rake parallel:create
  # - bundle exec rake parallel:prepare
  # - bundle exec rake parallel:spec
services:
  - postgres
notify:
  email:
    recipients:1
      - corey@jtrpfurniture.com
