image: ruby2.3.1
script:
  - bundle install
  - bundle exec rake parallel:create
  - bundle exec rake parallel:prepare
  - bundle exec rake parallel:spec
depends_on:
  - postgres
notify:
  email:
    recipients:1
      - corey@jtrpfurniture.com
