language: ruby
cache: bundler
rvm:
  - "2.3.1"
addons:
  postgresql: "9.4"
before_install: gem install bundler --pre
# before_script:
#   - psql --version
#   - psql -c 'create database travis_ci_test;' -U postgres
#   - cp config/database.yml.travis config/database.yml
#   - RAILS_ENV=test bundle exec rake db:test:prepare
