version: '2'

services:
  web:
    build: .
    command: ./script/start
    ports:
      - '3000:3000'
    volumes:
      - .:/jtrp
    volumes_from:
      - bundle
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  bundle:
    image: busybox
    volumes:
      - data-volume:/bundle

  db:
    image: 'postgres:9.6.2'
    environment:
      POSTGRES_USER: 'jtrp'
      POSTGRES_PASSWORD: 'yourpassword'
    ports:
      - '5432:5432'
    volumes:
      - data-volume:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:3.2-alpine
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - data-volume:/var/lib/redis/data

  phantomjs:
    image: wernight/phantomjs

  sidekiq:
    depends_on:
      - db
      - redis
      - web
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/jtrp
    volumes_from:
      - bundle
    env_file:
      - .env

volumes:
  data-volume:
