version: '2'

services:
  web:
    build: .
    command: ./script/start
    ports:
      - '3000:3000'
    volumes:
      - .:/jtrp
    volumes_from:
      - bundle
    environment:
      - POSTGRESQL_HOST=db
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - REDIS_DOMAIN=redis
      - REDIS_PORT=6379
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: always

  bundle:
    image: busybox
    volumes:
      - data-volume:/bundle

  db:
    image: 'postgres:9.6.2'
    ports:
      - '5432:5432'
    volumes:
      - data-volume:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:3.2-alpine
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - data-volume:/var/lib/redis/data

  phantomjs:
    image: wernight/phantomjs

  sidekiq:
    build: .
    depends_on:
      - db
      - redis
      - web
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/jtrp
    volumes_from:
      - bundle
    env_file:
      - .env

volumes:
  data-volume:
