version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/ruby:2.3.3-browsers
      - image: bitnami/postgresql:latest

    environment:
      TEST_RESULTS: /tmp/test-results
      RAILS_ENV: test

    steps:
      - checkout
      - type: cache-restore
        key: jtrp-{{ checksum "Gemfile.lock" }}

      - run: bundle install --path vendor/bundle

      # Store bundle cache
      - type: cache-save
        key: jtrp-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      - type: cache-restore
        key: nodejs
      - run:
          name: Install Nodejs
          command: sudo apt-get install nodejs

      - type: cache-save
        key: nodejs
        paths:
          - /usr/local/bin/nodejs

      # - type: cache-restore
      #   key: phantomjs
      - run: sudo curl --output /usr/local/bin/phantomjs https://s3.amazonaws.com/circle-downloads/phantomjs-2.1.1


        


      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

      # Run rspec in parallel
      - type: shell
        command: |
          bundle exec rspec --profile 10 \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml \
                            --format documentation \
                            $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

      # Save artifacts
      - type: store_test_results
        path: /tmp/test-results
