version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      # using custom image, see .circleci/images/primary/Dockerfile
      - image: circleci/ruby:2.3.3-browsers
      - image: bitnami/postgresql:latest

    environment:
      TEST_RESULTS: /tmp/test-results
      RAILS_ENV: test

    steps:
      - checkout
      - type: cache-restore
        key: jtrp-{{ checksum "Gemfile.lock" }}

      - run: sudo apt-get install nodejs

      - run: bundle install --path vendor/bundle

      # Store bundle cache
      - type: cache-save
        key: jtrp-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

      # Run rspec in parallel
      - type: shell
        command: |
          bundle exec rspec --profile 10 \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml \
                            --format progress \
                            $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

      # Save artifacts
      - type: store_test_results
        path: /tmp/test-results
