version: 2
jobs:
  build:
    working_directory: ~/jtrp
    docker:
      - image: circleci/ruby:2.3.3-node
      - image: circleci/postgres:9.5-alpine
      - image: selenium/standalone-chrome-debug
    steps:
      - checkout

      # Restore bundle cache
      - type: cache-restore
        key: jtrp-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle --jobs 20

      # Store bundle cache
      - type: cache-save
        key: jtrp-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load
      # 
      # - run:
      #   command: Xvfb :99
      #   background: true

      # Run rspec in parallel
      - type: shell
        command: |
          bundle exec rspec --profile 10 \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml \
                            --format documentation \
                            $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

      # Save artifacts
      - type: store_test_results
        path: /tmp/test-results
