default: &default
  adapter: postgresql
  encoding: unicode
  pool: 20

development:
  <<: *default
  database: jtrp_development

local:
  <<: *default
  database: jtrp_development

test:
  <<: *default
  database: jtrp_test

production:
  url:  <%= ENV["DATABASE_URL"] %>
