default: &default
  adapter: postgresql
  encoding: unicode
  pool: 25

development:
  <<: *default
  database: jtrp_development

local:
  <<: *default
  database: jtrp_development

test:
  <<: *default
  database: jtrp_test

production:
  <<: *default
  database: jtrp_production
  username: jtrp
  password: <%= ENV['JTRP_DATABASE_PASSWORD'] %>
