default: &default
  adapter: postgresql
  encoding: unicode
  pool: 20
  username: <%= ENV.fetch('POSTGRESQL_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('POSTGRESQL_PASSWORD', '') %>
  host: <%= ENV.fetch('POSTGRESQL_HOST', 'localhost') %>
  port: 5432

development:
  <<: *default
  database: jtrp_development

local:
  <<: *default
  database: jtrp_development

test:
  <<: *default
  database: jtrp_test<%= ENV['TEST_ENV_NUMBER'] %>

production:
  url:  <%= ENV["DATABASE_URL"] %>
