connections:
  
  default: &default
    sidekiq:
      url: <%= ENV['REDIS_URL'] %>

  production:
    <<: *default
    cache:
      url: <%= ENV['REDISCLOUD_URL'] %>

  development:
    <<: *default
    cache:
      url: <%= ENV['REDIS_URL'] %>/2
